services:
  database:
    image: 'postgre:latest'
    ports:
      - 15432:5432
    environment:
      - POSTGRES_PASSWORD=SnyderCut@214
    networks:
      - postgres-network

    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql

